# Generated by Django 3.1.4 on 2021-02-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0004_auto_20210131_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofilepage',
            name='type',
            field=models.CharField(default='supplier', max_length=256),
        ),
    ]
