# Generated by Django 3.1.4 on 2021-02-04 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0005_companyprofilepage_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestforproposals',
            name='paymentMethod',
        ),
    ]
