# Generated by Django 3.1.4 on 2021-02-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0006_remove_requestforproposals_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestforproposals',
            name='email',
            field=models.EmailField(default='vsevolod.pohvalenko@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='requestforproposals',
            name='paymentMethod',
            field=models.TextField(default='Google Pay'),
        ),
    ]
