# Generated by Django 3.1.4 on 2021-01-31 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20210131_0610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='owner',
        ),
        migrations.AddField(
            model_name='document',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='API.companyprofilepage'),
        ),
        migrations.AlterField(
            model_name='document',
            name='Title',
            field=models.CharField(default=' ', max_length=75),
        ),
    ]
